name: Test Python with Cache
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use python-cache-action
        uses: Drafteame/setup-ci-langs/@chore/poc-python-cache-action 
        with:
          enable-all: true
         
      
      - name: Install dependencies
        run: |
          poetry install

      - name: Verify cache path
        run: |
          if [ -d ~/.cache/pypoetry ]; then
            echo "Cache directory exists."
          else
            echo "Cache directory does not exist."
          fi

      - name: List cache directory
        run: ls -la ~/.cache/pypoetry