name: Test Python with Cache
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Python Cache Action
        uses: Drafteame/python-cache-action/@main 
        with:
          python-version: '3.12.0'
          poetry-version: '1.8.3'
         
      
      - name: Install dependencies
        run: |
          poetry install
          echo "Dependencies installed successfully."

      - name: Verify cache path
        run: |
          if [ -d ~/.cache/pypoetry ]; then
            echo "Cache directory exists."
          else
            echo "Cache directory does not exist."
          fi

      - name: List cache directory
        run: ls -la ~/.cache/pypoetry
